Hashtag:
  variants:
- form: hashtag
  needs_purity_estimation: false
  
- form: الهاشتاغ
  needs_putiry_estimation: false
  
- form: الوسم
  needs_putiry_estimation: true
  
- form: علامة التصنيف
  needs_putiry_estimation: false
