Hashtag:
  variants:
- form: hashtag
  needs_disambiguation: false
  
- form: الهاشتاغ
  needs_disambiguation: false
  
- form: الوسم
  needs_disambiguation: true
  
- form: علامة التصنيف
  needs_disambiguation: false
